server:
  port: 8081

spring:
  cloud:
    stream:
      function:
        definition : orderSupplier;paymentEventConsumer
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0 :
          destination: payment-event
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
